### ISSUE TITLE
Dont work?

### ISSUE THREAD

**Issue by fSociety-Protected** [MesrineNathanael/League-Orbwalker#1]
Aparrently, nothing appear when I try execute the Orbwalker.
Any help or fix?

**Comment by MesrineNathanael** [comment]
I just pushed a fix, it should be working now :) 

Remember to set the enemy HP bar color in the "settings" panel if you want to use the enemy detection and change your in game binding to the right ones specified in the "Settings" panel.

Let me know if it's working now

**Comment by fSociety-Protected** [comment]
Apparently, it compiles without any problem.

![image](https://user-images.githubusercontent.com/72263269/225818850-aff0cf12-2508-46bc-8add-f4a042e6f623.png)
                      · · ·

But the application still won't open. 🤔

PREVIEW  HERE   =   https://screenrec.com/share/pxrGbMn0HL

Anyway, if I try to compile the code, there are errors everywhere.
Example: 
![image](https://user-images.githubusercontent.com/72263269/225819884-090f34df-cf35-404c-b9b7-018a2bc09fad.png)

**Comment by fSociety-Protected** [comment]
**_A special .NET library may be required for your programme to work properly? 🥴_**

**Comment by MesrineNathanael** [comment]
Well that's strange, install .Net 6 framework and the .NET Desktop app developmcent kit in Visual Studio (It's made in WPF).

I've published a release with my config, give it a try (╯▽╰ )
https://github.com/MesrineNathanael/League-Orbwalker/releases/tag/v0.1

App screenshot
https://i.imgur.com/Yb2eRaw.png

**Comment by MesrineNathanael** [comment]
And I believe that the errors you had is cause the View of the app is not loaded up so it mess up everything :/
I can't really pin point what is wrong actually. 

Double check if the nuget package "HandyControl - 3.3.0" is installed maybe ?

**Comment by fSociety-Protected** [comment]
**_I'm going to give it a try right now, expect my comments in the next 5-10 minutes._**

**Comment by fSociety-Protected** [comment]
Yeah Nugget "HandyControl - 3.3.0" is installed.

![image](https://user-images.githubusercontent.com/72263269/225850892-55892142-abc3-4981-b896-92412922e93b.png)


> And I believe that the errors you had is cause the View of the app is not loaded up so it mess up everything :/ I can't really pin point what is wrong actually.
> 
> Double check if the nuget package "HandyControl - 3.3.0" is installed maybe ?

**Comment by fSociety-Protected** [comment]
**_Yeah, you're app you push on releases section WORK!_**

**_But IDK, why I can't mcake it work compiling the project.
Maybe somcething is corrupted on the project? 🥴🤔_**

**Comment by MesrineNathanael** [comment]
I don't know, I'm trying to compile it on another blank computer, I'll let you know if it work on my side

**Comment by fSociety-Protected** [comment]
**_Already know it, what happend.
I found the problem._**

**_When you push the release, you had one file named config.xml_**
**_Apparently, when I release it, this file was not generated.
This file is needed to load the form, and load the rest of the app._**

**_One thing, this work??_**
![image](https://user-images.githubusercontent.com/72263269/225858520-8ffea52a-b65a-44fd-bb1e-727554a73897.png)

**_Im trying to make it work, but atm, I cant..._**
